name: Attendance

on:
  repository_dispatch:
  
  schedule:
    - cron: 45 12 * * *
    
  watch:
    types: started
    
env:
  TZ: Asia/Shanghai
  
jobs:
  Auto-Attendance:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: checkout actions
      uses: actions/checkout@v1
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core python3-pip
        sudo timedatectl set-timezone "$TZ"

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        
    - name: Clone repo & Setup pip
      run: |
        echo 'Start Cloning'
        git clone https://github.com/thriving123/fuckTodayStudy.git --depth=1
        cd fuckTodayStudy
        pip3 install -r requirements.txt
      
    - name: Last Run
      run: |
        echo 'Start Running'
        mv $GITHUB_WORKSPACE/config.yml $GITHUB_WORKSPACE/fuckTodayStudy/config.yml
        mv $GITHUB_WORKSPACE/sign.jpg $GITHUB_WORKSPACE/fuckTodayStudy/sign.jpg
        mv $GITHUB_WORKSPACE/system.yml $GITHUB_WORKSPACE/fuckTodayStudy/login/system.yml
        cd $GITHUB_WORKSPACE/fuckTodayStudy
        python index.py
